name: Deploy docs with Quartz

on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v4

      - name: Clone target repo
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/solansea/quartz-docs-drawsteel-ru.git target-repo

      - name: Replace files
        run: |
          rm -rf target-repo/content/*
          cp -r ./* target-repo/content/

      - name: Commit & Push
        run: |
          cd target-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Sync docs from source repo" || echo "No changes to commit"
          git push
